app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='user'

urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('signup/',views.handlesignup,name='handlesignup'),
    path('signup_otp/', views.signup_otp, name='signup_otp'),
    path('resend_otp_signup', views.ResentOtpSignup, name='resend_otp_signup'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('password_verify/<uidb64>/<token>/', views.password_verify, name='password_verify'),
    path('confirm_password/', views.confirm_password, name='confirm_password'),
    path('login/',views.handlelogin,name='handlelogin'),
    path('logout/',views.logout,name='logout'),
    path('search/',views.search,name='search'),



]

cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    # user side
    path('cart/', views.cart, name='cart'),
    path('addcart/<int:product_id>/', views.addcart, name='addcart'),
    path('removecartitem/<int:product_id>/', views.removecartitem,
         name='removecartitem'),
    path('profile/', views.profile, name='profile'),
    path('address/', views.address, name='address'),
    path('addaddress/', views.addaddress, name='addaddress'),
    path('editaddress/<int:address_id>', views.editaddress, name='editaddress'),
    path('deleteaddress/<int:address_id>', views.deleteaddress, name='deleteaddress'),
    path('checkout/', views.checkout, name='checkout'),
    path('addaddresscheck/', views.addaddresscheck,
         name='addaddresscheck'),
    path('set_default_address/<int:address_id>/', views.set_default_address, name='set_default_address'),
    path('removecart/<int:product_id>/', views.removecart, name='removecart'),
    path('placeorder/', views.placeorder, name='placeorder'),
    path('increment/<int:product_id>/', views.increment,name='increment'),
    
    

]

dashboard/urls.py
from django.urls import path
from . import views


app_name = 'dashboard' 

urlpatterns = [
    path('adminlogin/', views.adminlogin, name="adminlogin"),
    path('admindash/', views.admindashboard, name="admindashboard"),
    path('adminlogout/', views.adminlogout, name='adminlogout'),
    path('usersdetails/', views.usersdetails, name="usersdetails"),
    path('userblock/<int:user_id>/', views.userblock, name="userblock"),
    path('wishlist/', views.wishlist, name="wishlist"),
    path('addwishlist/<int:variant_id>/', views.addwishlist, name='addwishlist'),
    path('removewish/<int:wish_id>', views.removewish, name='removewish'),
    path('addwishcart/<int:wish_id>', views.addwishcart, name='addwishcart'),
    path('get-sales-revenue/', views.get_sales_revenue,
         name='get_sales_revenue'),
    path('add_referral_program/', views.add_referral_program, name='add_referral_program'),
    path('edit_referral_program/<int:program_id>/', views.edit_referral_program, name='edit_referral_program'),
    path('deletereferral/<int:program_id>/', views.deletereferral, name='deletereferral'),
    path('myrefer/', views.myrefer, name='myrefer'),
]

eccom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('app.urls')),
    path('', include('products.urls')),
    path('', include('category.urls')),
    path('', include('dashboard.urls')),
    path('', include('cart.urls')),
    path('', include('order.urls')),
] 
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

order/urls.py
from django.urls import path
from . import views



app_name='order'

urlpatterns = [

    
   
    path('cashdelivery/<str:tracking_no>/', views.cashdelivery, name='cashdelivery'),
    path('razorpaid/<str:tracking_no>/', views.razorpaid, name='razorpaid'),
    path('orderinvoice/<int:order_id>/', views.orderinvoice, name='orderinvoice'),
    path('myorder', views.myorder, name='myorder'),
    path('myorderdetail/<int:order_id>/', views.myorderdetail, name='myorderdetail'),
    path('returnorder/<int:order_item_id>/', views.returnorder, name='returnorder'),
    path('cancelorder/<int:order_item_id>/', views.cancelorder, name='cancelorder'),
    path('mywallet', views.mywallet, name='mywallet'),
    path('walletpay/<int:order_id>/', views.walletpay, name='walletpay'),
    path('mycoupons/',views.mycoupons,name='mycoupons'),
    path('applycoupon/',views.applycoupon,name='applycoupon'),
    path('handlecancel/',views.handlecancel,name='handlecancel'),
    path('pdf-download/<int:id>', views.pdf_download, name='pdf_download'),
    path('callback/', views.callback, name='callback'),

   #admin
    path('vieworder/', views.vieworder, name='vieworder'),
    path('viewsingleadmin/<int:order_id>', views.viewsingleadmin, name='viewsingleadmin'),
    path('updatestatus/<int:order_id>/<str:new_status>/', views.updatestatus, name='updatestatus'),
    path('returnapprove/<int:order_id>', views.returnapprove, name='returnapprove'),
    path('viewcoupon/',views.viewcoupon,name='viewcoupon'),
    path('addcoupon/',views.addcoupon,name='addcoupon'),
    path('deletecoupon/<int:id>/', views.deletecoupon, name='deletecoupon'),
    path('editcoupon/<int:id>/', views.editcoupon, name='editcoupon'),
    path('salesreport/',views.salesreport,name='salesreport'),
    path('stockreport/',views.stock_report,name='stockreport'),
    path('sales-report-pdf/', views.sales_report_pdf_download, name='sales_report_pdf'),
   
]

products/urls.py
from django.urls import path
from . import views


app_name='products'

urlpatterns = [
     # user side
    path('home/', views.home, name='home'),
    path('viewshop/', views.viewshop, name='viewshop'),
    path('singleproduct/<int:product_id>/', views.singleproductview, name="singleproductview"),
     #admin side
    path('viewproduct/', views.viewproduct, name='viewproduct'),
    path('addproduct/', views.addproduct, name='addproduct'),
    path('softdeleteproduct/<int:product_id>/', views.softdeleteproduct, name='softdeleteproduct'),
    path('undosoftdeleteproduct/<int:product_id>/', views.undosoftdeleteproduct, name='undosoftdeleteproduct'),
    path('editproduct/<int:product_id>', views.editproduct, name='editproduct'),
    path('viewvariant/<int:variant_id>', views.viewvariant, name="viewvariant"),
    path('addvariant/', views.addvariant, name='addvariant'),
    path('editvariant/<int:variant_id>', views.editvariant, name="editvariant"),
    path('softdeletevariant/<int:variant_id>/', views.softdeletevariant, name='softdeletevariant'),
    path('undosoftdeletevariant/<int:variant_id>/', views.undosoftdeletevariant, name='undosoftdeletevariant'),
    path('viewimage/<int:product_id>', views.viewimage, name='viewimage'),
    path('addimage/<int:product_id>', views.addimage, name='addimage'),
    path('deleteimage/<int:image_id>', views.deleteimage, name='deleteimage'),
    path('searchadmin/', views.searchadmin, name='searchadmin'),
]

order/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from cart.models import Cart,CartItem,Address,Coupon,UserCoupons
from django.http import JsonResponse, HttpResponse
from django.contrib import messages
from user.models import User
from order.models import Order,OrderItem,Payment,ReturnOrder,UserWallet
from products.models import Product,ProductVariant
from django.db import transaction
from django.views.decorators.cache import cache_control
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist  
from datetime import datetime
import razorpay
import json
from django.template.loader import get_template
from io import BytesIO
from django.views import View
from django.db.models import Sum
import os
from xhtml2pdf import pisa
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt


# Create your views here.

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

@never_cache    
@login_required   
def razorpaid(request,tracking_no):
    user=request.user
    try:
        order = Order.objects.get(tracking_no=tracking_no, user=user)
        order_id = order.id
    except Order.DoesNotExist:
        return redirect('cart:cart')
    payment= Payment.objects.filter(user=user).order_by('-created_at').first()
    payment.save()
    order.payment=payment
    order.save()
    cart_id = _cart_id(request)
    cart = Cart.objects.get(cart_id=cart_id)
    cart_items = CartItem.objects.filter(cart=cart,is_active=True).order_by('id')
    
    
    for cart_item in cart_items:
        variant=cart_item.variant
        stock=variant.stock-cart_item.quantity
        variant.stock=stock
        variant.product.stock = stock   
        variant.save()   
        variant.product.save()
        if 'coupon_code' in request.session:
            coupon_code = request.session['coupon_code']
            coupon = Coupon.objects.get(coupon_code=coupon_code)
            discount = float(coupon.coupon_discount)
            pricevalue=cart_item.variant.discount_price-discount
        else:
            pricevalue=cart_item.variant.discount_price

        order_product = OrderItem.objects.create(
            order=order,
            user=user,
            product=cart_item.product,
            variant=cart_item.variant,
            quantity=cart_item.quantity,
            price=pricevalue,
            
        )
        order_product.save()
    
    cart_items.delete()
    if 'coupon_code' in request.session:
        del request.session['coupon_code']
   
    return redirect('order:orderinvoice', order_id=order_id)

@transaction.atomic
def cashdelivery(request,tracking_no):
    user=request.user
    try:
        order=Order.objects.get(user=user,tracking_no=tracking_no)
    except Order.DoesNotExist:
        return redirect('order:orderconfirm')
    total_amount= order.total_price
    payment=Payment.objects.create(user=user,payment_method="Cash On Delivery",amount_paid=total_amount,status="Not Paid")
    payment.save()
    order.payment=payment
    order.save()
    
    cart_id = _cart_id(request)
    cart = Cart.objects.get(cart_id=cart_id)
    cart_items = CartItem.objects.filter(cart=cart,is_active=True).order_by('id')
    
    
    for cart_item in cart_items:
        variant=cart_item.variant
        stock=variant.stock-cart_item.quantity
        variant.stock=stock
        variant.product.stock = stock
        variant.save()
        variant.product.save()
        if 'coupon_code' in request.session:
            coupon_code = request.session['coupon_code']
            coupon = Coupon.objects.get(coupon_code=coupon_code)
            discount = float(coupon.coupon_discount)
            pricevalue=cart_item.variant.discount_price-discount
        else:
            pricevalue=cart_item.variant.discount_price

        order_product = OrderItem.objects.create(
            order=order,
            user=user,
            product=cart_item.product,
            variant=cart_item.variant,
            quantity=cart_item.quantity,
            price=pricevalue,
            
        )
        order_product.save()
    
    cart_items.delete()
    if 'coupon_code' in request.session:
        del request.session['coupon_code']
    
    context = {'order': order}

    return render(request, 'order/cashdelivery.html', context)

@login_required
def orderinvoice(request,order_id):
    user = request.user
    order = Order.objects.get(id=order_id)
    order_items = OrderItem.objects.filter(order=order,user=user)
    payment = Payment.objects.filter(order=order,user=user)
    cart_items = CartItem.objects.filter(user=user)
    total = 0
    tax = 0
    discount = 0
    grand_total = 0
    subtotal = 0 
    for order_item in order_items:
        order_item_total = order_item.variant.discount_price * order_item.quantity
        subtotal += order_item_total
        total=subtotal  
    discount=order_item.variant.discount_price-order_item.price
    if discount != 0:
        total -= discount
    else:
        total=subtotal
    tax = (2 * total) / 100  
    grand_total = total + tax 

    context = {
        'order': order,
        'order_items': order_items,
        'payment': payment,
        'grand_total': grand_total,
        'cart_items': cart_items,
        'total': total,
        'tax':tax,
        'discount':discount,
        'subtotal': subtotal,
    }
    return render(request, 'order/orderconfirm.html', context)

def myorder(request):
    orders = Order.objects.filter(user=request.user,payment__isnull=False).order_by('-id')
    order_items = OrderItem.objects.filter(user=request.user).order_by('-id')
    context = {
        'orders': orders,
        "order_items": order_items,
    }
    return render(request, 'userprofile/myorder.html',context)
@login_required        
def myorderdetail(request,order_id):
    user=request.user  
    email = request.user
    user = User.objects.get(email=email)
    order = Order.objects.get(id=order_id)
    if request.method == "POST":
        status=request.POST.get('status')
        order = Order.objects.filter(user=user)
        if status == 'status' or status == 'all':
            order_items = OrderItem.objects.filter(user=user).order_by('-id')
        else:
            print(status)
            order_items = OrderItem.objects.filter(user=user,status=status).order_by('-id')
            order_items1 = OrderItem.objects.filter(user=user, status='Cancelled',).values()
            print(order_items1)
        context = {
            "order": order,
            "order_items": order_items
        }
    else:
        order_items = OrderItem.objects.filter(user=user,order=order).order_by('-id')
        context = {
            "order": order,
            "order_items": order_items
        }
    
    
    return render(request, 'userprofile/order.html', context)


@login_required
def cancelorder(request,order_item_id):
    order_item = OrderItem.objects.get(id=order_item_id)
    order = Order.objects.get(id=order_item.order.id)
    if order is not None:
        order.status = 'Cancelled'
        order.save()
        order_items = OrderItem.objects.filter(order=order)
        if order.payment.payment_method == 'Razorpay' or order.payment.payment_method == 'Wallet':
            email = request.user
            user = User.objects.get(email=email)
            userwallet = UserWallet()
            userwallet.user = request.user
            if userwallet is not None:
                userwallet.amount=UserWallet.objects.filter(user=user, transaction='Credited').aggregate(Sum('amount'))['amount__sum'] or 0
                userwallet.amount = (userwallet.amount or 0) + order.total_price
                userwallet.transaction = 'Credited'
                userwallet.save()
            user.save()
        for item in order_items:
            reason = request.POST.get('cancel')
            item.status = 'Cancelled'
            item.save()
        return redirect('order:myorder')    
    else:
        pass    

#<!---------admin---------->  
@login_required(login_url='/adminlogin/')
def vieworder(request):
    if request.method=="POST":
        status=request.POST.get('status')
        if status == 'status' or status == 'all':
            orders = Order.objects.filter(payment__isnull=False).order_by('-id')
        else:
            orders = Order.objects.filter(status=status,payment__isnull=False).order_by('-id')
        context = {
            'orders': orders
        }
        return render(request, 'admin/vieworder.html', context)
    else:
        orders = Order.objects.filter(payment__isnull=False).order_by('-id')
        context = {
            "orders": orders,
            
        }
        return render(request, 'admin/vieworder.html', context)
    
@login_required(login_url='/adminlogin/')    
def viewsingleadmin(request, order_id):
    order = Order.objects.get(id=order_id)
    order_item = OrderItem.objects.filter(order=order)
    user=User.objects.get(id=order.user.id)
    payments = Payment.objects.filter(order__id=order_id)
    subtotal=0
    discount=0
    total=0

    for item in order_item:
        item_total = item.variant.discount_price * item.quantity
        #total = item_total  
        subtotal += item_total
        total=subtotal
    discount=item.variant.discount_price-item.price  
    if discount != 0:
        total -= discount 
    else:
        total=subtotal
    tax = (2 * total) / 100
    grand_total = total + tax 
    
    user.save()
    context = {
        'order': order,
        'order_item': order_item,
        'payments': payments,
        'subtotal':subtotal,
        'discount':discount,
        'tax': tax,
        'total':total,
        'grand_total': grand_total,
        
        
    }

templates/userprofile/profileinfo.html
{% load static %}
<!DOCTYPE html>
<html lang="zxx">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="Ogani Template">
    <meta name="keywords" content="Ogani, unica, creative, html">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Footwear {% block 'title' %}{%endblock%}</title>

    <!-- Google Font -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.4.1/font/bootstrap-icons.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Cairo:wght@200;300;400;600;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <!-- Css Styles -->
   <!--<link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/elegant-icons.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/nice-select.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/jquery-ui.min.css' %}" type="text/css">
    <link rel="stylesheet" href="{% static 'css/user/owl.carousel.min.css' %} " type="text/css">-->
   <!-- <link rel="stylesheet" href="{% static 'css/slicknav.min.css' %}" type="text/css">-->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    {% block styles %}{%endblock%}
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-white h-4vh">
        <div class="container-fluid">
        <a class="navbar-brand " href="#"><img src="{% static 'images/trend.png' %}" alt="" width="125px"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse text-dark fw-bold" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'user:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'products:viewshop'%}">Shop </a>
              </li>
              <li class="nav-item">
              <a class="nav-link" href="{% url 'user:about' %}">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user:contact' %}">Contact Us</a>
              </li>
            </ul>
            <form action="{% url 'user:search' %}" method="get" class="d-flex">
             
                <input class="form-control  me-2" type="search" placeholder="Search" aria-label="Search" name="keyword">
                <button class="btn btn-outline-success bg-success text-white" type="submit" id="search-btn">Search</button>
              </form>
                
                  <div class="other-links me-auto mx-5 ml-3">
                    
                    {% if not request.user.is_authenticated %}
                    <a href="{% url 'user:handlesignup' %}"><button type="button btn-outline-dark">Account</button></a>
                    <i class="fa-solid fa-user "></i>
                    <a href="{% url 'cart:profile' %}"><button type="button btn-outline-dark">Profile</button></a>
                    {% else %}
                    <a href="{% url 'cart:profile' %}"><button type="button btn-outline-dark">Hi , {{user.name}}</button></a>
                    <a href="{% url 'user:logout' %}"><button type="button btn-outline-dark">Logout</button></a>
                    <i class="fa-solid fa-cart-shopping mx-5"></i>
                    {% endif %}
                </div>
                </div>
              </div>
            </div>
        </nav>
 
{% block content %}
{% endblock %}
<!-- Footer -->
<div class="container-fluid m-0 p-0">
    <div class="row">
        <div class="col-md-12">
            <footer class="page-footer font-small bg-secondary">
              <div class="container-fluid my-">

                <footer class="text-center text-lg-start fs-6 mt-xl-5 pt-1">
                <!-- Grid container -->
                <div class="container p-1 text-white">
                  <!--Grid row-->
                  <div class="row">
                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
                      <h5 class="text-capitalize mb-4">Quick Links</h5>
                      <ul class="list-unstyled mb-4">
                        <li>
                          <a href="#!" class="text-white text-decoration-none">About Us</a>
                        </li>
                        <li>
                          <a href="#!" class="text-white text-decoration-none">Collections</a>
                        </li>
                        <li>
                          <a href="#!" class="text-white text-decoration-none">Contact Us</a>
                        </li>
                      </ul>
                    </div>
                    <!--Grid column-->
            
                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
                      <h5 class="text-capitalize mb-4">Policies</h5>
            
                      <ul class="list-unstyled">
                        <li>
                          <a href="#!" class="text-white text-decoration-none">Shipping Delivery</a>
                        </li>
                        <li>
                          <a href="#!" class="text-white text-decoration-none">Privacy Policy</a>
                        </li>
                        <li>
                          <a href="#!" class="text-white text-decoration-none">Returns & Exchanges Poicy</a>
                        </li>
                        <li>
                          <a href="#!" class="text-white text-decoration-none">Payment</a>
                        </li>
                      </ul>
                    </div>
                    <!--Grid column-->
            
                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
                      <h5 class="text-capitalize mb-4">Catalog</h5>
                      
                      <ul class="list-unstyled">
                        <li>
                          <a href="#!" class="text-white text-decoration-none">Heels</a>
                        </li>
                        <li>
                          <a href="#!" class="text-white text-decoration-none">Loafers</a>
                        </li>
                        <li>
                          <a href="#!" class="text-white text-decoration-none">Casuals</a>
                        </li>
                        <li>
                          <a href="#!" class="text-white text-decoration-none">Ethnic Collections</a>
                        </li>
                      </ul>
                    </div>
                    <!--Grid column-->
            
                    <!--Grid column-->
                    <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
                      <h5 class="text-capitalize mb-4">Sign up to our newsletter</h5>
            
                      <div class="form-outline form-white mb-4">
                        <input type="email" id="form5Example2" class="form-control" />
                        <label class="form-label" form="form5Example2">Email address</label>
                      </div>
            
                      <button type="submit" class="btn btn-outline-dark bg-success btn-block">Subscribe</button>
                    </div>
                    <!--Grid column-->
                  </div>
                  <!--Grid row-->
                </div>
                <!-- Grid container -->
              </footer>
              
            </div>
            <!-- End of .container -->
            </footer>
            </div>
        </div>
    </div>


    

    <!-- Js Plugins -->
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
            integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM"
            crossorigin="anonymous"></script>
    {% block j-script %}{% endblock %}
    <!-- Js Plugins -->
    <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
   
    <!--<script src="{% static 'js/bootstrap.min.js'%}"></script>
    <script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
    <script src="{% static 'js/jquery-ui.min.js'%}"></script>
    <script src="{% static 'js/jquery.slicknav.js'%}"></script>
    <script src="{% static 'js/mixitup.min.js'%}"></script>
    <script src="{% static 'js/main.js'%}"></script>-->
    
    
</body>

</html>

templates/userprofile/wishlist.html
{% extends 'userprofile/profileinfo.html' %}
{% load static %}
{% block title %}
User profile
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="breadcrumb-section breadcrumb-bg">
            <div class="col-lg-12 text-center" style="background-image: url('{% static '/images/femal.jpg' %}'); background-size: cover; width:100%; height:280px;">
                <div class="breadcrumb-text">
                  <ol class="breadcrumb justify-content-center mb-0">
                    <li class="breadcrumb-item active text-dark fw-bold" aria-current="page"><a class="text-decoration-none text-dark" href="{% url 'cart:profile' %}">Your Profile</a></li>
                    <li class="breadcrumb-item active text-dark fw-bold" aria-current="page">Wishlist</li>
                </div>  
            </div>
        </div>
    </div>
</div>
<div>
    {% if messages %}
    <div class="container" style="background-color:transparent;">
        <ul class="messages mx-auto text-center">
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                 {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
</div>
<div class="container-fluid">
    <div class="row">
  <div class="col-lg-12 col-md-12">
    {% if not wishlist %}
    <h2 class="text-center mt-4">Your wishlist is empty!!!!</h2>
    <br>
    <div class="text-center mb-4 mt-3">
        <a href="{% url 'products:viewshop'%}" class="boxed-btn black">Continue Shopping</a>
    </div>
    {% else %}
<section class="shoping-cart spad">
 <div class="container mt-4">
 <div class="row">
    <div class="col-lg-1">
    </div>
   <div class="col-lg-10">
        <div class="shoping__cart__table mt-4">
     <table class="table text-start align-middle table-bordered table-hover mb-0 table-stripped">
        <thead>
        <tr>
            <th class="shoping__product">Products</th>
            <th> Details</th>
            <th>Price</th>
            <th></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        {% for item in wishlist %}
        <tr>
            <td class="shoping__cart__item">
                <a href="#" class="text-decoration-none text-dark">
                    <img src="{{ item.variant.product.images.url }}" alt="" width="100px">
                    <h5>{{item.variant.product.product_name}}</h5>
                </a>

            </td>
            <td class="shoping__cart__price">Size: {{item.variant.size}},
                <br>
                Colour: {{item.variant.color}},
                <br>
                Material: {{item.variant.material}}
            </td>
            <td class="shoping__cart__price">
                ₹ {{item.variant.discount_price}}
            </td>

            <td class="shoping__cart__total">
               <a href="{% url 'dashboard:addwishcart' wish_id=item.id %}" class="btn btn-warning">Add to Cart</a>
            </td>
            <td class="shoping__cart__item__close">
                <a href="{% url 'dashboard:removewish' wish_id=item.id %}">
                    <i class="material-icons" data-toggle="tooltip" title="Delete" style="color: red;">delete</i>
                </a>
            </td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
  </div>

           </div>
        </div>
    </div>
<div class="row px-4 ">
    <div class="col-lg-12 text-center">
        <div class="shopping__cart__btns">
        <a href="{% url "products:viewshop" %}" class=" mt-3 btn btn-info text-decoration-none">
            Continue Shopping
        </a>

        </div>
    </div>
</div>
    </section>
    {% endif %}

  </div>

</div>
</div>
{% endblock %}