app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='user'

urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('signup/',views.handlesignup,name='handlesignup'),
    path('signup_otp/', views.signup_otp, name='signup_otp'),
    path('resend_otp_signup', views.ResentOtpSignup, name='resend_otp_signup'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('password_verify/<uidb64>/<token>/', views.password_verify, name='password_verify'),
    path('confirm_password/', views.confirm_password, name='confirm_password'),
    path('login/',views.handlelogin,name='handlelogin'),
    path('logout/',views.logout,name='logout'),
    path('search/',views.search,name='search'),



]

cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    # user side
    path('cart/', views.cart, name='cart'),
    path('addcart/<int:product_id>/', views.addcart, name='addcart'),
    path('removecartitem/<int:product_id>/', views.removecartitem,
         name='removecartitem'),
    path('profile/', views.profile, name='profile'),
    path('address/', views.address, name='address'),
    path('addaddress/', views.addaddress, name='addaddress'),
    path('editaddress/<int:address_id>', views.editaddress, name='editaddress'),
    path('deleteaddress/<int:address_id>', views.deleteaddress, name='deleteaddress'),
    path('checkout/', views.checkout, name='checkout'),
    path('addaddresscheck/', views.addaddresscheck,
         name='addaddresscheck'),
    path('set_default_address/<int:address_id>/', views.set_default_address, name='set_default_address'),
    path('removecart/<int:product_id>/', views.removecart, name='removecart'),
    path('placeorder/', views.placeorder, name='placeorder'),
    path('increment/<int:product_id>/', views.increment,name='increment'),
    
    

]

category/urls.py
from django.urls import path
from . import views

app_name='category'

urlpatterns = [
    #admin side
    #subcategory
    path('viewsubcategory/', views.viewsubcategory, name='viewsubcategory'),
    path('subunlist/<int:subcat_id>/', views.subunlist, name="subunlist"),
    path('addsubcategory/', views.addsubcategory, name='addsubcategory'),
    path('editsubcategory/<int:subcat_id>/', views.editsubcategory, name="editsubcategory"),
    #category
    path('viewcategory/', views.viewcategory, name='viewcategory'),
    path('catunlist/<int:cat_id>/', views.catunlist, name="catunlist"),
    path('addcategory/', views.addcategory, name='addcategory'),
    path('editcategory/<int:category_id>/', views.editcategory, name="editcategory"),


    # user side
    path('showcategoryproduct/<int:cat_id>/', views.showcategoryproduct, name="showcategoryproduct"),
    
]

dashboard/urls.py
from django.urls import path
from . import views


app_name = 'dashboard' 

urlpatterns = [
    path('adminlogin/', views.adminlogin, name="adminlogin"),
    path('admindash/', views.admindashboard, name="admindashboard"),
    path('adminlogout/', views.adminlogout, name='adminlogout'),
    path('usersdetails/', views.usersdetails, name="usersdetails"),
    path('userblock/<int:user_id>/', views.userblock, name="userblock"),
    path('wishlist/', views.wishlist, name="wishlist"),
    path('addwishlist/<int:variant_id>/', views.addwishlist, name='addwishlist'),
    path('removewish/<int:wish_id>', views.removewish, name='removewish'),
    path('addwishcart/<int:wish_id>', views.addwishcart, name='addwishcart'),
    path('get-sales-revenue/', views.get_sales_revenue,
         name='get_sales_revenue'),
    path('add_referral_program/', views.add_referral_program, name='add_referral_program'),
    path('edit_referral_program/<int:program_id>/', views.edit_referral_program, name='edit_referral_program'),
    path('deletereferral/<int:program_id>/', views.deletereferral, name='deletereferral'),
    path('myrefer/', views.myrefer, name='myrefer'),
]

eccom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('app.urls')),
    path('', include('products.urls')),
    path('', include('category.urls')),
    path('', include('dashboard.urls')),
    path('', include('cart.urls')),
    path('', include('order.urls')),
] 
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

products/urls.py
from django.urls import path
from . import views


app_name='products'

urlpatterns = [
     # user side
    path('home/', views.home, name='home'),
    path('viewshop/', views.viewshop, name='viewshop'),
    path('singleproduct/<int:product_id>/', views.singleproductview, name="singleproductview"),
     #admin side
    path('viewproduct/', views.viewproduct, name='viewproduct'),
    path('addproduct/', views.addproduct, name='addproduct'),
    path('softdeleteproduct/<int:product_id>/', views.softdeleteproduct, name='softdeleteproduct'),
    path('undosoftdeleteproduct/<int:product_id>/', views.undosoftdeleteproduct, name='undosoftdeleteproduct'),
    path('editproduct/<int:product_id>', views.editproduct, name='editproduct'),
    path('viewvariant/<int:variant_id>', views.viewvariant, name="viewvariant"),
    path('addvariant/', views.addvariant, name='addvariant'),
    path('editvariant/<int:variant_id>', views.editvariant, name="editvariant"),
    path('softdeletevariant/<int:variant_id>/', views.softdeletevariant, name='softdeletevariant'),
    path('undosoftdeletevariant/<int:variant_id>/', views.undosoftdeletevariant, name='undosoftdeletevariant'),
    path('viewimage/<int:product_id>', views.viewimage, name='viewimage'),
    path('addimage/<int:product_id>', views.addimage, name='addimage'),
    path('deleteimage/<int:image_id>', views.deleteimage, name='deleteimage'),
    path('searchadmin/', views.searchadmin, name='searchadmin'),
]

products/models.py
from django.db import models
from category.models import Category, Sub_Category

# Create your models here.

class Product(models.Model):
    product_name = models.CharField(max_length=200, unique=True)
    images = models.ImageField(upload_to="images/products/",default=None)
    is_available = models.BooleanField(default=True)
    description = models.TextField(max_length=225, blank=True)
    original_price = models.FloatField(default=0)
    discount_price = models.FloatField(default=0)
    stock = models.IntegerField(default=0)
    category= models.ForeignKey(Category, on_delete=models.CASCADE)
    subcategory= models.ForeignKey(Sub_Category, on_delete=models.CASCADE)
    is_visible = models.BooleanField(default=True)

    def __str__(self):
        return self.product_name
    
class ProductVariant(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='variants')
    size=models.CharField(max_length=10)
    color = models.CharField(max_length=50)
    material = models.CharField(max_length=50)
    original_price = models.FloatField(default=0)
    discount_price = models.FloatField(default=0)
    stock = models.IntegerField()
    is_available = models.BooleanField(default=True)
    def __str__(self):
        return f"{self.product.product_name}"
    
class ProductImage(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)  # Change related_name
    image = models.ImageField(upload_to='images/product_images/')

    


    
# Create your models here.

products/views.py
from django.shortcuts import render,redirect
from django.core.paginator import Paginator
from .models import Product,ProductVariant,ProductImage
from category.models import Sub_Category,Category
from django.shortcuts import get_object_or_404
from django.core.exceptions import ValidationError
import re
from django.db.models import Q
import os
from eccom import settings
from decimal import Decimal
from django.contrib import messages
from django.urls import reverse
from cart.views import _cart_id
from cart.models import CartItem


# Create your views here.
def home(request):
    products = Product.objects.filter(is_visible=True).order_by('id')
    sub_cat = Sub_Category.objects.filter(is_visible=True).order_by('id')
    cat = Category.objects.filter(is_visible=True)
    products_with_default_variants = Product.objects.prefetch_related('variants').filter(
        variants__is_available=True)
    product_queryset = ProductVariant.objects.none()
    for products in products_with_default_variants:
        default_variant = products.variants.filter(is_available=True).first()
        if default_variant:
            product_queryset |= ProductVariant.objects.filter(pk=default_variant.pk)
            
    context = {
        'products': product_queryset,
        'sub_cat': sub_cat,
        'category': cat,

    }

    return render(request, 'user/index.html', context)

def remove_currency_symbols(input_string):
    # Define a regular expression pattern to match dollar ($) and rupee (₹) symbols
    currency_symbols = r'[$₹]'
    # Use the sub() function from the re module to replace the currency symbols with an empty string
    output_string = re.sub(currency_symbols, '', input_string)
    return output_string

from django.db.models import QuerySet
def viewshop(request):
    if request.method == 'POST':
        minamount = int(remove_currency_symbols(request.POST.get('minamount')))
        maxamount = int(remove_currency_symbols(request.POST.get('maxamount')))
        filter_size=request.POST.get('filter_size')

        if minamount and maxamount and filter_size is not None:
            print("hooo", minamount, maxamount)
            products_within_price_range = ProductVariant.objects.filter(discount_price__gte=minamount,
                                                                        discount_price__lte=maxamount,
                                                                        size=filter_size)
        else:
            products_within_price_range = ProductVariant.objects.filter(discount_price__gte=minamount,
                                                                        discount_price__lte=maxamount)
            if filter_size is None:
                filter_size = 0
        paginator = Paginator(products_within_price_range, 26)
        page_number = request.GET.get('page', 1)
        products_within_price_range = paginator.get_page(page_number)
        sub_cat = Category.objects.filter(is_visible=True)
        context = {
            'products': products_within_price_range,
            'all_products': products_within_price_range,
            'sale_off': products_within_price_range,
            'sub_category': sub_cat,
            'min': minamount,
            'max': maxamount,
            'size': str(filter_size)
        }
        return render(request, 'products/shop.html', context)
    
    else:
        products_with_default_variants = Product.objects.prefetch_related('variants').filter(
           variants__is_available=True)
        product_queryset = ProductVariant.objects.none()
        for product in products_with_default_variants:
            default_variant = product.variants.filter(is_available=True).first()
            if default_variant:
                product_queryset |= ProductVariant.objects.filter(pk=default_variant.pk)
                

        sub_cat = Category.objects.filter(is_visible=True)
        paginator = Paginator(product_queryset, 16)
        page_number = request.GET.get('page', 1)
        product_queryset = paginator.get_page(page_number)
        context = {
            'products': product_queryset,
            'all_products': product_queryset,
            'sale_off': product_queryset,
            'sorted_product': product_queryset,
            'sub_category': sub_cat,

        }
        return render(request, 'products/shop.html', context)
    

def singleproductview(request,product_id):
    selected_product = ProductVariant.objects.get(id=product_id)
    product = Product.objects.get(id=selected_product.product.id)
    product_variant = ProductVariant.objects.filter(product=product)
    print(selected_product,product,product_variant)
    cart_id = _cart_id(request)
    in_cart = CartItem.objects.filter(cart__cart_id=cart_id, product=product).exists()
    images = ProductImage.objects.filter(product=product)
    imagesa = ProductImage.objects.filter(product=product).first()
    similar_product = ProductVariant.objects.filter(product__category=product.category)[:4]
    
    like_product=ProductVariant.objects.filter(product__category=product.category,discount_price__lt=4000)[:4]

    # try:
    #     orderproduct = OrderItem.objects.filter(user=request.user,product = product).exists()
    # except OrderItem.DoesNotExist:
    #     orderproduct = None

    # get the review
    
    context = {
        'product': selected_product,
        'variants': product_variant,
        'in_cart': in_cart,
        'images': images,
        # 'orderproduct': orderproduct,
        #'reviews': reviews,
        'similar_product': similar_product,
        'like_product': like_product,
    }
    return render(request, 'products/singleproduct.html', context)


#<!--Admin view product--->
def viewproduct(request):
    products = Product.objects.filter(is_visible=True).order_by('id')
    sub_cat = Sub_Category.objects.filter(is_visible=True).order_by('id')
    paginator = Paginator(products, 3)
    page_number = request.GET.get('page', 1)
    products = paginator.get_page(page_number)
    context = {
        'products': products,
        'sub_cat': sub_cat,

    }
    return render(request,"admin/viewproduct.html",context)
#<!--Admin view product--->
#<!--Admin softdelete product--->

def softdeleteproduct(request, product_id):
    try:
        product = Product.objects.get(pk=product_id)
    except Product.DoesNotExist:
        return redirect('/viewproduct/')
    product.soft_deleted = True
    product.is_available = False
    product.save()
    return redirect('/viewproduct/')

def undosoftdeleteproduct(request, product_id):
    try:
        product = Product.objects.get(pk=product_id)
    except Product.DoesNotExist:
        return redirect('/viewproduct/')
    product.soft_deleted = False
    product.is_available = True
    product.save()
    return redirect('/viewproduct/')

#<!--Admin add product--->
def addproduct(request):
    url = request.META.get('HTTP_REFERER')
    product = Product()
    if request.method == 'POST':
        product_name = request.POST.get('product_name')
        if Product.objects.filter(product_name=product_name).exists():
            messages.warning(request,"Product name already exist..!")
            return redirect(url)
        else:
            product.product_name = request.POST.get('product_name')
       
        product.description = request.POST.get('description')
        subcategory = request.POST.get('category_name')
        sub_cat = Sub_Category.objects.get(id=subcategory)
        product.subcategory = sub_cat
        product.category = sub_cat.category
        product.original_price = request.POST.get('original_price')
        product.discount_price = request.POST.get('discount_price')
        images = request.FILES.getlist('images')
        if images:
            product.images = images[len(images) - 1]

        product.save()   
        return redirect('/viewproduct/')
        

    return render(request, 'admin/viewproduct.html')

#<!--admin edit  ---------------------------------->
def editproduct(request, product_id):
    product = Product.objects.get(id=product_id)
    if request.method == 'POST':
        product.product_name = request.POST.get('product_name')
        product.description = request.POST.get('description')
        subcategory = request.POST.get('category_name')
        sub_cat = Sub_Category.objects.get(id=subcategory)
        product.subcategory = sub_cat
        product.category = sub_cat.category
        img1 = request.FILES.get('img')
        if img1 is None:
            product.images = product.images
        else:
            product.images = request.FILES.get('img')
        # product.stock = request.POST.get('stock')
        product.save()
        variant_size = request.POST.getlist("variant_size[]")
        original_price = request.POST.getlist("variant_original_price[]")
        discount_price = request.POST.getlist("variant_discount_price[]")
        stocks = request.POST.getlist('variant_stock[]')
        for size, original_price, discount_price, stock in zip(variant_size, original_price, discount_price,
                                                                stocks):
            if size and original_price and discount_price and stock:
                variant = ProductVariant()
                variant.product = product
                variant.size = Decimal(size)
                variant.original_price = Decimal(original_price)
                variant.discount_price = Decimal(discount_price)
                variant.stock = stocks
                variant.save()

        return redirect('/viewproduct/')
    return redirect('/viewproduct/')

#<!--admin view variant ---------------------------------->        
def viewvariant(request, variant_id):
    product = Product.objects.get(id=variant_id) 
    close_alert = request.GET.get('close_alert', False)
    variants = ProductVariant.objects.filter(product=product).order_by('id') 
    context = {
        'variants': variants, 
    }

templates/products/shop.html
{% extends 'user/base.html' %}
{% load static %}

{% block title %}
Shop
{% endblock %}
{% block styles %}
<style>
  .featured-icons .fa {
    visibility: hidden;
   
  }

  .col-md-3:hover .featured-icons .fa {
    visibility: visible;
  }
  

</style>
{%endblock%}
{% block content %}
<!-- Breadcrumb Section Begin -->
<div class="container-fluid page-header py-5">
    <div class="row">
        <div class="col-lg-12">
      <nav aria-label="breadcrumb" style="background-image: url('{% static '/images/adobe.jpg' %}'); background-size: cover; width:100%; height:250px;">
    <ol class="breadcrumb justify-content-center mb-0">
      <li class="breadcrumb-item"><a class="text-decoration-none text-dark fw-bold" href="{% url 'user:index' %}">Home</a></li>
      <li class="breadcrumb-item active text-dark fw-bold" aria-current="page">Shop</li>
    </ol>
  </nav>
</div>
</div>
</div>
  <!-- Breadcrumb Section End -->
   <!-- Product Section Begin -->
   <div class="container-fluid">
    <div class="row">
      <div class="col-lg-2 col-md-4">
        <div class="sidebar">
            <div class="hero__categories mb-5">
                    <ul style="list-style-type: none;">
                        <li><a class="text-decoration-none fs-4" style="color:#B22222;" href="{% url 'products:viewshop'%}">CATEGORIES</a>
                          {% for cat in sub_category %} 
                        <li><a class="text-decoration-none text-dark" href="{% url 'category:showcategoryproduct' cat_id=cat.id %}">{{cat.category_name}}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </div>
            <form method="post">
                {% csrf_token %}
                <div class="sidebar mx-3">
                        <p class="fs-3" style="color:#B22222;">Price</p>
                        <div class="price-range-wrap">
                            <div class="price-range ui-slider ui-corner-all ui-slider-horizontal ui-widget ui-widget-content"
                                 {% if min %} data-min="{{min}}" {% else %} data-min="10" {% endif %} {% if max %}
                                 data-max="{{max}}" {% else %} data-max="2000" {% endif %} >
                                <div class="ui-slider-range ui-corner-all ui-widget-header"></div>
                                <span tabindex="0" class="ui-slider-handle ui-corner-all ui-state-default"></span>
                                <span tabindex="0" class="ui-slider-handle ui-corner-all ui-state-default"></span>
                            </div>
                            <div class="range-slider">
                                <div class="price-input">
                                    <input type="text" id="minamount" name="minamount" value="100">
                                    <input class="my-2" type="text" id="maxamount" name="maxamount" value="8000">
                                </div>
                            </div>
                        </div>
    
                </div>
                <div class="sidebar__item mx-2 my-2">
                    <p class="fs-3" style="color:#B22222;">Popular Size</p>
                    <div class="sidebar__item__size">
                        <label class="size-label" for="large">
                            <input type="radio" id="large" name="filter_size" value="6UK" {% if size == 6UK %} checked {% else %} {% endif %}>
                            <span class="checkmark"></span>
                            6UK
                        </label>
                    </div>
                    <div class="sidebar__item__size">
                        <label class="size-label" for="medium">
                            <input type="radio" id="medium" name="filter_size" value="7UK"  {% if size == 7UK %} checked {% else %} {% endif %}>
                            <span class="checkmark"></span>
                            7UK
                        </label>
                    </div>
                    <div class="sidebar__item__size">
                        <label class="size-label" for="small">
                            <input type="radio" id="small" name="filter_size" value="8UK"  {% if size == 8UK %} checked {% else %} {% endif %}>
                            <span class="checkmark"></span>
                            8UK
                        </label>
                    </div>
                </div>

                <button type="submit" class="btn btn-primary my-2 mx-3">filter</button>
            </form>
        </div>
    </div>
    <!--Filter section for categories-->
    {% if cat_products %}
    <div class="col-lg-10 col-md-8 d-flex flex-column">
        <div class="row">
          {% for product in cat_products %}
          <div class="col-md-3 mt-3 position-relative">
            <div class="card mx-2" style="width:15rem;border:none" >
                <a href="{% url 'products:singleproductview' product_id=product.id %}"> 
                    <img src="/media/{{product.product.images}}" class="card-img-top" alt="" ></a>
            <div class="card-body text-center">
              <h6 class="card-title text-center" id="namepr{{product.id}}">{{product.product.product_name}}</h6>
              <div class="text-center">
                <span class="price fw-bold">₹ {{product.discount_price}}</span>
               
              </div>
              <div class="featured-icons mt-2">
                <a href="{% url 'dashboard:addwishlist' variant_id=product.id%}" class="text-decoration-none mx-2"><i class="fa fa-heart fs-5"style="color:#E9967A;" title="Add to Wishlist"></i></a>
                <a href="{% url 'cart:addcart' product.id %}" class="text-decoration-none btn btn-block px-3"style="background-color:#E9967A;">Add Cart</a>
              </div>
            </div>
          </div>
          </div>
          {% endfor %}

        </div>
      <!-- <nav aria-label="...">
            <ul class="pagination">
                {% if products.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ products.previous_page_number }}">Previous</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                {% endif %}
                {% for i in products.paginator.page_range %}
                {% if products.number == i %}
                <li class="page-item active" aria-current="page">
                    <span class="page-link">{{ i }}</span>
                </li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if products.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ products.next_page_number }}">Next</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true">Next</a>
                </li>
                {% endif %}
            </ul>
        </nav>-->
    </div>
    {% else %}
    {% if sale_off %}
    <div class="col-lg-10 col-md-8 d-flex flex-column">
        <div class="product__discount">
            <div class="section-title product__discount__title">
                <h2 class="text-center" style="color: #FF6347;"></h2>
            </div>
            <div class="row">
                
            </div>
        </div>
        {% if all_products %}
        <div class="filter__item">
            <div class="row">
                <div class="col-lg-4 col-md-5">

                </div>
                <div class="col-lg-4 col-md-4 ">
                    <div class="filter__found">
                        <!--<h6>Other Products </h6>-->
                    </div>
                </div>

            </div>
        </div>
        <div class="row">
          {% for variant in all_products %}
          <div class="col-md-3 mt-3 position-relative">
            <div class="card mx-1" style="width:15rem;border:none" >
                <a href="{% url 'products:singleproductview' product_id=variant.id %}">
                    <img src="/media/{{variant.product.images}}" class="card-img-top" alt="" ></a>
            <div class="card-body text-center">
              <h6 class="card-title text-center" id="namepr{{variant.product.id}}">{{variant.product.product_name}}</h6>
              <p>Product ID: {{variant.product.id}}</p>
              <div class="text-center">
                <span class="price fw-bold">₹ {{variant.product.discount_price}}</span>
              </div>
              <div class="featured-icons mt-2">
                {% if variant.stock == 0 or product.stock == 0 %}
                <p class="text-danger">Out of Stock</p>
                {% else %}
                <a href="{% url 'cart:addcart' product_id=variant.id %}" class="text-decoration-none btn btn-block px-3"style="background-color:#E9967A;">Add Cart</a>
                <a href="{% url 'dashboard:addwishlist' variant_id=variant.id%}" class="text-decoration-none mx-2"><i class="fa fa-heart fs-5"style="color:#E9967A;" title="Add to Wishlist"></i></a>
                {% endif %}
              </div>
              
            </div>
          </div>
          </div>
          {% endfor %}

        </div>
        <!--                padgination-->
        <nav aria-label="...">
            <ul class="pagination">
                {% if cat_products.has_previous %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ cat_products.previous_page_number }}">Previous</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true">Previous</a>
                </li>
                {% endif %}
                {% for i in cat_products.paginator.page_range %}
                {% if cat_products.number == i %}
                <li class="page-item active" aria-current="page">
                    <span class="page-link">{{ i }}</span>
                </li>
                {% else %}
                <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                {% endif %}
                {% endfor %}
                {% if cat_products.has_next %}
                <li class="page-item">
                    <a class="page-link" href="?page={{ cat_products.next_page_number }}">Next</a>
                </li>
                {% else %}
                <li class="page-item disabled">
                    <a class="page-link" tabindex="-1" aria-disabled="true">Next</a>
                </li>
                {% endif %}
            </ul>
        </nav>
    </div>
    {% endif %}
    {% endif %}
    {% endif %}
    </div>
  </div>
{% endblock %}

{% block j-script %}
<script>
        $(function() {
            const slider = $('.price-range');
            const minAmount = $("#minamount");
            const maxAmount = $("#maxamount");

            slider.slider({
                range: true,
                min: 10,
                max: 2000,
                values: [10, 2000],
                slide: function(event, ui) {
                    minAmount.val("₹"+ui.values[0]);
                    maxAmount.val("₹"+ui.values[1]);
                }
            });
        });


</script>
{% endblock %}