app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='user'

urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('signup/',views.handlesignup,name='handlesignup'),
    path('signup_otp/', views.signup_otp, name='signup_otp'),
    path('resend_otp_signup', views.ResentOtpSignup, name='resend_otp_signup'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('password_verify/<uidb64>/<token>/', views.password_verify, name='password_verify'),
    path('confirm_password/', views.confirm_password, name='confirm_password'),
    path('login/',views.handlelogin,name='handlelogin'),
    path('logout/',views.logout,name='logout'),
    path('search/',views.search,name='search'),



]

cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    # user side
    path('cart/', views.cart, name='cart'),
    path('addcart/<int:product_id>/', views.addcart, name='addcart'),
    path('removecartitem/<int:product_id>/', views.removecartitem,
         name='removecartitem'),
    path('profile/', views.profile, name='profile'),
    path('address/', views.address, name='address'),
    path('addaddress/', views.addaddress, name='addaddress'),
    path('editaddress/<int:address_id>', views.editaddress, name='editaddress'),
    path('deleteaddress/<int:address_id>', views.deleteaddress, name='deleteaddress'),
    path('checkout/', views.checkout, name='checkout'),
    path('addaddresscheck/', views.addaddresscheck,
         name='addaddresscheck'),
    path('set_default_address/<int:address_id>/', views.set_default_address, name='set_default_address'),
    path('removecart/<int:product_id>/', views.removecart, name='removecart'),
    path('placeorder/', views.placeorder, name='placeorder'),
    path('increment/<int:product_id>/', views.increment,name='increment'),
    
    

]

eccom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('app.urls')),
    path('', include('products.urls')),
    path('', include('category.urls')),
    path('', include('dashboard.urls')),
    path('', include('cart.urls')),
    path('', include('order.urls')),
] 
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

order/urls.py
from django.urls import path
from . import views



app_name='order'

urlpatterns = [

    
   
    path('cashdelivery/<str:tracking_no>/', views.cashdelivery, name='cashdelivery'),
    path('razorpaid/<str:tracking_no>/', views.razorpaid, name='razorpaid'),
    path('orderinvoice/<int:order_id>/', views.orderinvoice, name='orderinvoice'),
    path('myorder', views.myorder, name='myorder'),
    path('myorderdetail/<int:order_id>/', views.myorderdetail, name='myorderdetail'),
    path('returnorder/<int:order_item_id>/', views.returnorder, name='returnorder'),
    path('cancelorder/<int:order_item_id>/', views.cancelorder, name='cancelorder'),
    path('mywallet', views.mywallet, name='mywallet'),
    path('walletpay/<int:order_id>/', views.walletpay, name='walletpay'),
    path('mycoupons/',views.mycoupons,name='mycoupons'),
    path('applycoupon/',views.applycoupon,name='applycoupon'),
    path('handlecancel/',views.handlecancel,name='handlecancel'),
    path('pdf-download/<int:id>', views.pdf_download, name='pdf_download'),
    path('callback/', views.callback, name='callback'),

   #admin
    path('vieworder/', views.vieworder, name='vieworder'),
    path('viewsingleadmin/<int:order_id>', views.viewsingleadmin, name='viewsingleadmin'),
    path('updatestatus/<int:order_id>/<str:new_status>/', views.updatestatus, name='updatestatus'),
    path('returnapprove/<int:order_id>', views.returnapprove, name='returnapprove'),
    path('viewcoupon/',views.viewcoupon,name='viewcoupon'),
    path('addcoupon/',views.addcoupon,name='addcoupon'),
    path('deletecoupon/<int:id>/', views.deletecoupon, name='deletecoupon'),
    path('editcoupon/<int:id>/', views.editcoupon, name='editcoupon'),
    path('salesreport/',views.salesreport,name='salesreport'),
    path('stockreport/',views.stock_report,name='stockreport'),
    path('sales-report-pdf/', views.sales_report_pdf_download, name='sales_report_pdf'),
   
]

products/urls.py
from django.urls import path
from . import views


app_name='products'

urlpatterns = [
     # user side
    path('home/', views.home, name='home'),
    path('viewshop/', views.viewshop, name='viewshop'),
    path('singleproduct/<int:product_id>/', views.singleproductview, name="singleproductview"),
     #admin side
    path('viewproduct/', views.viewproduct, name='viewproduct'),
    path('addproduct/', views.addproduct, name='addproduct'),
    path('softdeleteproduct/<int:product_id>/', views.softdeleteproduct, name='softdeleteproduct'),
    path('undosoftdeleteproduct/<int:product_id>/', views.undosoftdeleteproduct, name='undosoftdeleteproduct'),
    path('editproduct/<int:product_id>', views.editproduct, name='editproduct'),
    path('viewvariant/<int:variant_id>', views.viewvariant, name="viewvariant"),
    path('addvariant/', views.addvariant, name='addvariant'),
    path('editvariant/<int:variant_id>', views.editvariant, name="editvariant"),
    path('softdeletevariant/<int:variant_id>/', views.softdeletevariant, name='softdeletevariant'),
    path('undosoftdeletevariant/<int:variant_id>/', views.undosoftdeletevariant, name='undosoftdeletevariant'),
    path('viewimage/<int:product_id>', views.viewimage, name='viewimage'),
    path('addimage/<int:product_id>', views.addimage, name='addimage'),
    path('deleteimage/<int:image_id>', views.deleteimage, name='deleteimage'),
    path('searchadmin/', views.searchadmin, name='searchadmin'),
]

order/views.py
from django.shortcuts import render,redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import never_cache
from cart.models import Cart,CartItem,Address,Coupon,UserCoupons
from django.http import JsonResponse, HttpResponse
from django.contrib import messages
from user.models import User
from order.models import Order,OrderItem,Payment,ReturnOrder,UserWallet
from products.models import Product,ProductVariant
from django.db import transaction
from django.views.decorators.cache import cache_control
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist  
from datetime import datetime
import razorpay
import json
from django.template.loader import get_template
from io import BytesIO
from django.views import View
from django.db.models import Sum
import os
from xhtml2pdf import pisa
from django.conf import settings
from django.views.decorators.csrf import csrf_exempt


# Create your views here.

def _cart_id(request):
    cart=request.session.session_key
    if not cart:
        cart=request.session.create()
    return cart

@never_cache    
@login_required   
def razorpaid(request,tracking_no):
    user=request.user
    try:
        order = Order.objects.get(tracking_no=tracking_no, user=user)
        order_id = order.id
    except Order.DoesNotExist:
        return redirect('cart:cart')
    payment= Payment.objects.filter(user=user).order_by('-created_at').first()
    payment.save()
    order.payment=payment
    order.save()
    cart_id = _cart_id(request)
    cart = Cart.objects.get(cart_id=cart_id)
    cart_items = CartItem.objects.filter(cart=cart,is_active=True).order_by('id')
    
    
    for cart_item in cart_items:
        variant=cart_item.variant
        stock=variant.stock-cart_item.quantity
        variant.stock=stock
        variant.product.stock = stock   
        variant.save()   
        variant.product.save()
        if 'coupon_code' in request.session:
            coupon_code = request.session['coupon_code']
            coupon = Coupon.objects.get(coupon_code=coupon_code)
            discount = float(coupon.coupon_discount)
            pricevalue=cart_item.variant.discount_price-discount
        else:
            pricevalue=cart_item.variant.discount_price

        order_product = OrderItem.objects.create(
            order=order,
            user=user,
            product=cart_item.product,
            variant=cart_item.variant,
            quantity=cart_item.quantity,
            price=pricevalue,
            
        )
        order_product.save()
    
    cart_items.delete()
    if 'coupon_code' in request.session:
        del request.session['coupon_code']
   
    return redirect('order:orderinvoice', order_id=order_id)

@transaction.atomic
def cashdelivery(request,tracking_no):
    user=request.user
    try:
        order=Order.objects.get(user=user,tracking_no=tracking_no)
    except Order.DoesNotExist:
        return redirect('order:orderconfirm')
    total_amount= order.total_price
    payment=Payment.objects.create(user=user,payment_method="Cash On Delivery",amount_paid=total_amount,status="Not Paid")
    payment.save()
    order.payment=payment
    order.save()
    
    cart_id = _cart_id(request)
    cart = Cart.objects.get(cart_id=cart_id)
    cart_items = CartItem.objects.filter(cart=cart,is_active=True).order_by('id')
    
    
    for cart_item in cart_items:
        variant=cart_item.variant
        stock=variant.stock-cart_item.quantity
        variant.stock=stock
        variant.product.stock = stock
        variant.save()
        variant.product.save()
        if 'coupon_code' in request.session:
            coupon_code = request.session['coupon_code']
            coupon = Coupon.objects.get(coupon_code=coupon_code)
            discount = float(coupon.coupon_discount)
            pricevalue=cart_item.variant.discount_price-discount
        else:
            pricevalue=cart_item.variant.discount_price

        order_product = OrderItem.objects.create(
            order=order,
            user=user,
            product=cart_item.product,
            variant=cart_item.variant,
            quantity=cart_item.quantity,
            price=pricevalue,
            
        )
        order_product.save()
    
    cart_items.delete()
    if 'coupon_code' in request.session:
        del request.session['coupon_code']
    
    context = {'order': order}

    return render(request, 'order/cashdelivery.html', context)

@login_required
def orderinvoice(request,order_id):
    user = request.user
    order = Order.objects.get(id=order_id)
    order_items = OrderItem.objects.filter(order=order,user=user)
    payment = Payment.objects.filter(order=order,user=user)
    cart_items = CartItem.objects.filter(user=user)
    total = 0
    tax = 0
    discount = 0
    grand_total = 0
    subtotal = 0 
    for order_item in order_items:
        order_item_total = order_item.variant.discount_price * order_item.quantity
        subtotal += order_item_total
        total=subtotal  
    discount=order_item.variant.discount_price-order_item.price
    if discount != 0:
        total -= discount
    else:
        total=subtotal
    tax = (2 * total) / 100  
    grand_total = total + tax 

    context = {
        'order': order,
        'order_items': order_items,
        'payment': payment,
        'grand_total': grand_total,
        'cart_items': cart_items,
        'total': total,
        'tax':tax,
        'discount':discount,
        'subtotal': subtotal,
    }
    return render(request, 'order/orderconfirm.html', context)

def myorder(request):
    orders = Order.objects.filter(user=request.user,payment__isnull=False).order_by('-id')
    order_items = OrderItem.objects.filter(user=request.user).order_by('-id')
    context = {
        'orders': orders,
        "order_items": order_items,
    }
    return render(request, 'userprofile/myorder.html',context)
@login_required        
def myorderdetail(request,order_id):
    user=request.user  
    email = request.user
    user = User.objects.get(email=email)
    order = Order.objects.get(id=order_id)
    if request.method == "POST":
        status=request.POST.get('status')
        order = Order.objects.filter(user=user)
        if status == 'status' or status == 'all':
            order_items = OrderItem.objects.filter(user=user).order_by('-id')
        else:
            print(status)
            order_items = OrderItem.objects.filter(user=user,status=status).order_by('-id')
            order_items1 = OrderItem.objects.filter(user=user, status='Cancelled',).values()
            print(order_items1)
        context = {
            "order": order,
            "order_items": order_items
        }
    else:
        order_items = OrderItem.objects.filter(user=user,order=order).order_by('-id')
        context = {
            "order": order,
            "order_items": order_items
        }
    
    
    return render(request, 'userprofile/order.html', context)


@login_required
def cancelorder(request,order_item_id):
    order_item = OrderItem.objects.get(id=order_item_id)
    order = Order.objects.get(id=order_item.order.id)
    if order is not None:
        order.status = 'Cancelled'
        order.save()
        order_items = OrderItem.objects.filter(order=order)
        if order.payment.payment_method == 'Razorpay' or order.payment.payment_method == 'Wallet':
            email = request.user
            user = User.objects.get(email=email)
            userwallet = UserWallet()
            userwallet.user = request.user
            if userwallet is not None:
                userwallet.amount=UserWallet.objects.filter(user=user, transaction='Credited').aggregate(Sum('amount'))['amount__sum'] or 0
                userwallet.amount = (userwallet.amount or 0) + order.total_price
                userwallet.transaction = 'Credited'
                userwallet.save()
            user.save()
        for item in order_items:
            reason = request.POST.get('cancel')
            item.status = 'Cancelled'
            item.save()
        return redirect('order:myorder')    
    else:
        pass    

#<!---------admin---------->  
@login_required(login_url='/adminlogin/')
def vieworder(request):
    if request.method=="POST":
        status=request.POST.get('status')
        if status == 'status' or status == 'all':
            orders = Order.objects.filter(payment__isnull=False).order_by('-id')
        else:
            orders = Order.objects.filter(status=status,payment__isnull=False).order_by('-id')
        context = {
            'orders': orders
        }
        return render(request, 'admin/vieworder.html', context)
    else:
        orders = Order.objects.filter(payment__isnull=False).order_by('-id')
        context = {
            "orders": orders,
            
        }
        return render(request, 'admin/vieworder.html', context)
    
@login_required(login_url='/adminlogin/')    
def viewsingleadmin(request, order_id):
    order = Order.objects.get(id=order_id)
    order_item = OrderItem.objects.filter(order=order)
    user=User.objects.get(id=order.user.id)
    payments = Payment.objects.filter(order__id=order_id)
    subtotal=0
    discount=0
    total=0

    for item in order_item:
        item_total = item.variant.discount_price * item.quantity
        #total = item_total  
        subtotal += item_total
        total=subtotal
    discount=item.variant.discount_price-item.price  
    if discount != 0:
        total -= discount 
    else:
        total=subtotal
    tax = (2 * total) / 100
    grand_total = total + tax 
    
    user.save()
    context = {
        'order': order,
        'order_item': order_item,
        'payments': payments,
        'subtotal':subtotal,
        'discount':discount,
        'tax': tax,
        'total':total,
        'grand_total': grand_total,
        
        
    }

templates/order/cashdelivery.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %}
Orderconfirm
{% endblock %}
{% block content %}

<div class="container-fluid p-0">
    <div vlass="row">
        <div class="col-lg-12 p-0">
            <nav aria-label="breadcrumb" style="background-image: url('{% static '/images/newyear.jpg' %}'); background-size: cover; width:100%; height:250px;">
                <ol class="breadcrumb justify-content-center mb-0">
                  <li class="breadcrumb-item active text-dark fw-bold">Checkout</a></li>
                  <li class="breadcrumb-item active text-dark fw-bold"><a class="text-decoration-none text-dark" href="#">Placeorder</a></li>
                  <li class="breadcrumb-item active text-dark fw-bold" aria-current="page">OrderSuccess</li>
            </nav>
        </div>
    </div>
    <div class="container" style="margin-top:50px">
        <center><i class="fas fa-check-circle" style="font-size: 72px;margin-bottom: 20px;color: #28A745;"></i></center>
        <h2 class="text-center">Order Placed!</h2>
        <br>
        <div class="text-center">
            <a href="{% url 'products:viewshop' %}" class="btn btn-success">Shop more</a>
           
        </div>
    
    </div>
    <div class="cart-buttons text-center">
        <a type="button" href="{% url 'products:viewshop' %}" class="boxed-btn black text-decoration-none fs-4 btn btn-warning btn-md btn-block">Continue Shopping</a>
        <a href="{% url 'order:orderinvoice' order_id=order.id %}" class="boxed-btn black text-decoration-none fs-4 btn btn-warning btn-md btn-block">Order Invoice</a>
    </div>



</div>
{% endblock %}

templates/order/paymentfailure.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %}
Paymnetfailure
{% endblock %}
{% block style %}
<style>
    body {
        font-family: Arial, sans-serif;
        background-color: #f4f4f4;
        text-align: center;
        padding: 50px;
    }
    .container {
        background-color: #fff;
        padding: 20px;
        border-radius: 5px;
        box-shadow: 0 2px 10px rgba(0, 0, 0, 0.1);
    }
    h1 {
        color: #e74c3c;
    }
    p {
        color: #333;
    }
    .button {
        display: inline-block;
        padding: 10px 20px;
        background-color: #e74c3c;
        color: #fff;
        text-decoration: none;
        border-radius: 5px;
    }
    .button:hover {
        background-color: #c0392b;
    }
</style>
{% endblock %}
{% block content %}
<div class="container"> 
    <h1>Payment Failed</h1>
    <p>Oops! It seems there was an issue with your payment.</p>
    <p>Please try again or <a href="#">contact support</a> if the problem persists.</p>
    <a class="button" href="{% url 'products:viewshop' %}">Continue SHopping</a>
</div>
{% endblock %}

templates/order/placeorder.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %}
Order
{% endblock %}
{% block content %}
<div class="container-fluid">
    <div vlass="row">
        <div class="col-lg-12">
            <nav aria-label="breadcrumb" style="background-image: url('{% static '/images/cartbread.jpg' %}'); background-size: cover; width:100%; height:150px;">
                <ol class="breadcrumb justify-content-center mb-0">
                  <li class="breadcrumb-item"><a class="text-decoration-none text-dark fw-bold" href="{% url 'products:viewshop' %}">Shop</a></li>
                  <li class="breadcrumb-item active text-dark fw-bold"><a class="text-decoration-none text-dark" href="{% url 'cart:cart' %}">Cart</a></li>
                  <li class="breadcrumb-item active text-dark fw-bold" aria-current="page">Checkout</li>
                  <li class="breadcrumb-item active text-dark fw-bold" aria-current="page">Payment</li>
            </nav>
        </div>
    </div>
</div>
<div>
    {% if messages %}
    <div class="container" style="background-color:transparent;">
        <ul class="messages mx-auto text-center">
            {% for message in messages %}
            <div id="message">
                <div style="background-color:transparent;" class="error-alert {% if message.tags %}alert-{{ message.tags }}{% endif %}" role="alert">
                    <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
                    {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %} {% endif %}
                    {{ message }}
                </div>
            </div>
            {% endfor %}
        </ul>
    </div>
    {% endif %}
</div>

<div class="container-fluid">
    <div class="row">
        <div class="col-lg-12 col-md-12">
            <div class="card">
                <h5 class="card-header">Billing Address</h5>
                <div class="card-body">
                  <p class="card-text mb-0">{{order.address.recipient_name}}</p>
                  <p class="card-text mb-0">{{order.address.street_name}}</p>
                  <p class="card-text mb-0">{{order.address.village_name}} - {{order.address.postal_code}}</p>
                  <p class="card-text mb-0">{{order.address.email}}</p>
                  <p class="card-text mb-0">{{order.address.mobile}}</p>
                </div>
            </div>
            <br>					
            <div class="card">
                <h5 class="card-header">Review Products</h5>
                <div class="card-body">
                    <table class="table  align-middle border-collapse: collapse;
                    width: 80 %; margin:auto; mx-3">
                        <thead>
                            <tr>
                                <th>Products</th>
                                <th>Quantity</th>
                                <th>Price</th>
                                
                            </tr>
                        </thead>
                        <tbody class="order-details-body">
                            {% for cart_item in cart_items %}
                                <tr>
                                    <td class="product-image">  <a href="{% url 'products:singleproductview' product_id=cart_item.variant.id %}">
                                        <img src="{{ cart_item.product.images.url }}" alt="" width="100px">
                                    </a></td>
                                    <td>{{ cart_item.quantity }}</td>
                                    <td>₹{{ cart_item.variant.discount_price }}</td>
                                    
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-5">
            <div class="total-section ">
                <table class="total-table ">
                    <thead class="total-table-head">
                        <tr class="table-total-row">
                            <th></th>
                            <th><h4>Price</h4></th>
                        </tr>
                    </thead>
                   
                        <tbody class="mx-3">
                        <tr class="total-data  fs-6" >
                            <td><strong>Subtotal: </strong></td>
                            <td>₹ {{total}}</td>
                        </tr>
                        <tr class="total-data fs-6">
                            <td><strong>GST: </strong></td>
                            <td>₹ {{tax}}</td>
                        </tr>
                        {% if discount != 0 %}
                        <tr class="total-data fs-6">
                            <td><strong>Discount: </strong></td>
                            <td>₹ {{discount}}</td>
                        </tr>
                        {% endif %}
                        <tr class="total-data text-danger fs-5" >
                            <td><strong>Grand Total : </strong></td>
                            <td> ₹ {{total_price}}</td>
                        </tr>
                    </tbody>
                </table>
                <div class="cart-buttons mt-3 ">
                    <a type="button" href="{% url 'order:cashdelivery' tracking_no=order.tracking_no  %}" class="btn btn-warning btn-md btn-block">Cash On Delivery</a>
                    <a type="button" href="{% url 'order:walletpay' order_id=order.id %}" class="btn btn-warning btn-md btn-block wallet-button mx-2" style="background-color: #F28123;" >Pay with Wallet</a>
                    <button id="rzp-button1" type="submit" class="btn btn-primary btn-md btn-block">Pay with Razorpay</button>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>
<form method="POST">
<script src="https://checkout.razorpay.com/v1/checkout.js"></script>
<script>
    var options = {
        key: "rzp_test_zLLrBmHDjYzLTa" ,
        amount: "{{r_tot}}" ,
        currency: "INR",
        name: "TrendyFoot",
        description: "Test Transaction",
        image: "https://example.com/your_logo",
        order_id: "{{ paymentt.id }}", 
        callback_url: "{{callback_url}}",
        redirect: true,
        
         notes: {
        "address": "Razorpay Corporate Office"
        },
      
        theme: {
            "color": "#3399cc"
        }
    };

    var rzp1 = new Razorpay(options);
    document.getElementById('rzp-button1').onclick = function(e){
    rzp1.open();
    }
    
   
    
 </script>
<input type="hidden" custom="Hidden Element" name="hidden">
</form>
{% endblock %}

templates/order/sucessorder.html
{% extends 'user/base.html' %}
{% load static %}
{% block title %}
Razorconfirm
{% endblock %}
{% block content %}
<div class="container-fluid p-0">
    <div vlass="row">
        <div class="col-lg-12 p-0">
            <nav aria-label="breadcrumb" style="background-image: url('{% static '/images/newyear.jpg' %}'); background-size: cover; width:100%; height:250px;">
                <ol class="breadcrumb justify-content-center mb-0">
                  <li class="breadcrumb-item active text-dark fw-bold">Checkout</a></li>
                  <li class="breadcrumb-item active text-dark fw-bold"><a class="text-decoration-none text-dark" href="#">Placeorder</a></li>
                  <li class="breadcrumb-item active text-dark fw-bold" aria-current="page">PaymentSuccess</li>
            </nav>
        </div>
    </div>
    <section>
    <div class="container mt-3">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title mb-4 text-success">Order Placed Successfully (Razorpay)</h4>
                        <p>Your order has been successfully placed using Razorpay. Thank you for shopping with us!</p>
                        
                        <p>Payment Method: Razorpay</p>
                        <p>Your payment has been processed successfully.</p>
                    </div> 
                </div> 
                <div class="cart-buttons text-center mt-3">
                    <a type="button" href="{% url 'products:viewshop' %}" class="boxed-btn black text-decoration-none fs-5 btn btn-warning btn-md btn-block">Continue Shopping</a>
                    <a href="{% url 'order:razorpaid' tracking_no=order.tracking_no %}" class="boxed-btn black text-decoration-none fs-5 btn btn-warning btn-md btn-block mx-2">Order Invoice</a>
                </div>
              
            </div>   
        </div>
    </div> 
</section>
{% endblock %}