app/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

app_name='user'

urlpatterns = [
    path('',views.index,name='index'),
    path('about/',views.about,name='about'),
    path('contact/',views.contact,name='contact'),
    path('signup/',views.handlesignup,name='handlesignup'),
    path('signup_otp/', views.signup_otp, name='signup_otp'),
    path('resend_otp_signup', views.ResentOtpSignup, name='resend_otp_signup'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('password_verify/<uidb64>/<token>/', views.password_verify, name='password_verify'),
    path('confirm_password/', views.confirm_password, name='confirm_password'),
    path('login/',views.handlelogin,name='handlelogin'),
    path('logout/',views.logout,name='logout'),
    path('search/',views.search,name='search'),



]

cart/urls.py
from django.urls import path
from . import views

app_name='cart'

urlpatterns = [
    # user side
    path('cart/', views.cart, name='cart'),
    path('addcart/<int:product_id>/', views.addcart, name='addcart'),
    path('removecartitem/<int:product_id>/', views.removecartitem,
         name='removecartitem'),
    path('profile/', views.profile, name='profile'),
    path('address/', views.address, name='address'),
    path('addaddress/', views.addaddress, name='addaddress'),
    path('editaddress/<int:address_id>', views.editaddress, name='editaddress'),
    path('deleteaddress/<int:address_id>', views.deleteaddress, name='deleteaddress'),
    path('checkout/', views.checkout, name='checkout'),
    path('addaddresscheck/', views.addaddresscheck,
         name='addaddresscheck'),
    path('set_default_address/<int:address_id>/', views.set_default_address, name='set_default_address'),
    path('removecart/<int:product_id>/', views.removecart, name='removecart'),
    path('placeorder/', views.placeorder, name='placeorder'),
    path('increment/<int:product_id>/', views.increment,name='increment'),
    
    

]

dashboard/urls.py
from django.urls import path
from . import views


app_name = 'dashboard' 

urlpatterns = [
    path('adminlogin/', views.adminlogin, name="adminlogin"),
    path('admindash/', views.admindashboard, name="admindashboard"),
    path('adminlogout/', views.adminlogout, name='adminlogout'),
    path('usersdetails/', views.usersdetails, name="usersdetails"),
    path('userblock/<int:user_id>/', views.userblock, name="userblock"),
    path('wishlist/', views.wishlist, name="wishlist"),
    path('addwishlist/<int:variant_id>/', views.addwishlist, name='addwishlist'),
    path('removewish/<int:wish_id>', views.removewish, name='removewish'),
    path('addwishcart/<int:wish_id>', views.addwishcart, name='addwishcart'),
    path('get-sales-revenue/', views.get_sales_revenue,
         name='get_sales_revenue'),
    path('add_referral_program/', views.add_referral_program, name='add_referral_program'),
    path('edit_referral_program/<int:program_id>/', views.edit_referral_program, name='edit_referral_program'),
    path('deletereferral/<int:program_id>/', views.deletereferral, name='deletereferral'),
    path('myrefer/', views.myrefer, name='myrefer'),
]

eccom/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('user.urls')),
    path('', include('app.urls')),
    path('', include('products.urls')),
    path('', include('category.urls')),
    path('', include('dashboard.urls')),
    path('', include('cart.urls')),
    path('', include('order.urls')),
] 
if settings.DEBUG:
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )

products/urls.py
from django.urls import path
from . import views


app_name='products'

urlpatterns = [
     # user side
    path('home/', views.home, name='home'),
    path('viewshop/', views.viewshop, name='viewshop'),
    path('singleproduct/<int:product_id>/', views.singleproductview, name="singleproductview"),
     #admin side
    path('viewproduct/', views.viewproduct, name='viewproduct'),
    path('addproduct/', views.addproduct, name='addproduct'),
    path('softdeleteproduct/<int:product_id>/', views.softdeleteproduct, name='softdeleteproduct'),
    path('undosoftdeleteproduct/<int:product_id>/', views.undosoftdeleteproduct, name='undosoftdeleteproduct'),
    path('editproduct/<int:product_id>', views.editproduct, name='editproduct'),
    path('viewvariant/<int:variant_id>', views.viewvariant, name="viewvariant"),
    path('addvariant/', views.addvariant, name='addvariant'),
    path('editvariant/<int:variant_id>', views.editvariant, name="editvariant"),
    path('softdeletevariant/<int:variant_id>/', views.softdeletevariant, name='softdeletevariant'),
    path('undosoftdeletevariant/<int:variant_id>/', views.undosoftdeletevariant, name='undosoftdeletevariant'),
    path('viewimage/<int:product_id>', views.viewimage, name='viewimage'),
    path('addimage/<int:product_id>', views.addimage, name='addimage'),
    path('deleteimage/<int:image_id>', views.deleteimage, name='deleteimage'),
    path('searchadmin/', views.searchadmin, name='searchadmin'),
]

user/urls.py
from django.urls import path
from . import views



urlpatterns = [
   
]

user/models.py
from django.db import models

# Create your models here.
# Create your models here.
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager

# Create your models here.

class User_manager(BaseUserManager):
    def create_user(self, name, email, mobile, password=None):
        if not email:
            raise ValueError('User must have an email address')
        
        user = self.model(
            email=self.normalize_email(email),
            name=name,
            mobile=mobile
        )
        user.set_password(password)
        user.save(using=self._db)
        return user
    
    def create_superuser(self, name, email, mobile, password):
        user = self.create_user(
            email = self.normalize_email(email),
            password = password,
            name = name,
            mobile = mobile
        )

        user.is_admin = True
        user.is_active = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

    


class User(AbstractBaseUser):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100, unique=True)
    mobile = models.CharField(max_length=50, unique=True)

    date_joined = models.DateTimeField(auto_now_add=True)
    last_login = models.DateTimeField(auto_now_add=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['name','mobile']

    objects = User_manager()

    def __str__(self):
        return self.email
    
    def has_module_perms(self, add_label):
        return True
    def has_perm(self, perm, obj=None):
        return self.is_admin
    

templates/user/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Footwear</title>
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css">
    <!-- bootstrap links -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
   

    <!-- bootstrap links -->

</head>
<body> 
    <!--top navbar-->
    <nav class="navbar navbar-expand-lg navbar-light bg-white h-4vh">
        <div class="container-fluid">
        <a class="navbar-brand " href="#"><img src="{% static 'images/trend.png' %}" alt="" width="125px"></a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse text-dark fw-bold" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'user:index' %}">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'products:viewshop'%}">Shop </a>
              </li>
              <li class="nav-item">
              <a class="nav-link" href="{% url 'user:about' %}">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'user:contact' %}">Contact Us</a>
              </li>
            </ul>
            <form action="{% url 'user:search' %}" method="get" class="d-flex">
             
                <input class="form-control  me-2" type="search" placeholder="Search" aria-label="Search" name="keyword">
                <button class="btn btn-outline-success bg-success text-white" type="submit" id="search-btn">Search</button>
              </form>
                
                  <div class="other-links me-auto mx-5 ml-3">
                   
                    {% if not request.user.is_authenticated %}
                    <a href="{% url 'user:handlesignup' %}"><button type="button btn-outline-dark">Account</button></a>
                    <i class="fa-solid fa-user mx-2"></i>
                    <a href="{% url 'user:handlelogin' %}"><button type="button btn-outline-dark">Profile</button></a>
                    {% else %}
                    {% if not request.user.is_superuser %}
                    <a href="{% url 'cart:profile' %}"><button type="button btn-outline-dark">Hi {{user.name}}</button></a>
                    {% endif %}
                    <a href="{% url 'user:logout' %}"><button type="button btn-outline-dark">Logout</button></a>
                    <i class="fa-solid fa-cart-shopping mx-5"></i>
                    {% endif %}
                </div>
                </div>
              </div>
            </div>
        </nav>
         
          <!-- navbar -->
          <div class="container-fluid m-0">
          {% block content %}
          {% endblock %}
          </div>
          <!-- Footer -->
          <div class="container-fluid m-0 p-0">
            <div class="row">
                <div class="col-md-12">
                    <footer class="page-footer font-small bg-secondary">
                      <div class="container-fluid my-">

                        <footer class="text-center text-lg-start fs-6 mt-xl-5 pt-1">
                        <!-- Grid container -->
                        <div class="container p-1 text-white">
                          <!--Grid row-->
                          <div class="row">
                            <!--Grid column-->
                            <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
                              <h5 class="text-capitalize mb-4">Quick Links</h5>
                              <ul class="list-unstyled mb-4">
                                <li>
                                  <a href="#!" class="text-white text-decoration-none">About Us</a>
                                </li>
                                <li>
                                  <a href="#!" class="text-white text-decoration-none">Collections</a>
                                </li>
                                <li>
                                  <a href="#!" class="text-white text-decoration-none">Contact Us</a>
                                </li>
                              </ul>
                            </div>
                            <!--Grid column-->
                    
                            <!--Grid column-->
                            <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
                              <h5 class="text-capitalize mb-4">Policies</h5>
                    
                              <ul class="list-unstyled">
                                <li>
                                  <a href="#!" class="text-white text-decoration-none">Shipping Delivery</a>
                                </li>
                                <li>
                                  <a href="#!" class="text-white text-decoration-none">Privacy Policy</a>
                                </li>
                                <li>
                                  <a href="#!" class="text-white text-decoration-none">Returns & Exchanges Poicy</a>
                                </li>
                                <li>
                                  <a href="#!" class="text-white text-decoration-none">Payment</a>
                                </li>
                              </ul>
                            </div>
                            <!--Grid column-->
                    
                            <!--Grid column-->
                            <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
                              <h5 class="text-capitalize mb-4">Catalog</h5>
                              
                              <ul class="list-unstyled">
                                <li>
                                  <a href="#!" class="text-white text-decoration-none">Heels</a>
                                </li>
                                <li>
                                  <a href="#!" class="text-white text-decoration-none">Loafers</a>
                                </li>
                                <li>
                                  <a href="#!" class="text-white text-decoration-none">Casuals</a>
                                </li>
                                <li>
                                  <a href="#!" class="text-white text-decoration-none">Ethnic Collections</a>
                                </li>
                              </ul>
                            </div>
                            <!--Grid column-->
                    
                            <!--Grid column-->
                            <div class="col-lg-3 col-md-6 mb-4 mb-lg-0">
                              <h5 class="text-capitalize mb-4">Sign up to our newsletter</h5>
                    
                              <div class="form-outline form-white mb-4">
                                <input type="email" id="form5Example2" class="form-control" />
                                <label class="form-label" form="form5Example2">Email address</label>
                              </div>
                    
                              <button type="submit" class="btn btn-outline-dark bg-success btn-block">Subscribe</button>
                            </div>
                            <!--Grid column-->
                          </div>
                          <!--Grid row-->
                        </div>
                        <!-- Grid container -->
                      </footer>
                      
                    </div>
                    <!-- End of .container -->
                    </footer>
                    </div>
                </div>
            </div>
            <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
            <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
          <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
          <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
          {% block j-script %}{% endblock %}
         <!-- Js Plugins -->
         <script src="{% static 'js/jquery-3.3.1.min.js' %}"></script>
         <script src="{% static 'js/jquery-ui.min.js'%}"></script>
         <!-- Js Plugins -->
         

        </body>
        </html>

templates/user/index.html
{% extends 'user/base.html' %}
{% block title %}
Home

{% endblock %}
{% block content %}
<style>
  .featured-icons .fa {
    visibility: hidden;
  }

  .col-md-3:hover .featured-icons .fa {
    visibility: visible;
  }
  
  .carousel-item img{
    height:450px; /* set the height for the uniformity
  }
  
  object-fit:contain;
</style>
    {% load static %}
    <div class='container-fluid m-0 p-0'>
    <div class='col-md-12 col-sm-12 text-center'>
        <div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
              <li data-target="#carouselExampleCaptions" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
              <div class="carousel-item active">
                <img src="{% static '/images/myown.jpg' %}" class="slide d-block w-100" alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h2> Comfort is Priority</h2>
                    <button class="btn btn-outline-dark bg-secondary-50" type="submit" id="submit-btn">SHOP NOW</button>
                  
                </div>
              </div>
              <div class="carousel-item">
                <img src="{% static '/images/jam.png' %}" class="slide d-block w-100 " alt="...">
                <div class="carousel-caption d-none d-md-block">
                    <h2> New Arrivals Upto 30% Off</h2>
                    <button class="btn btn-outline-dark bg-white" type="submit" id="submit-btn">SHOP NOW</button>
                  
                </div>
              </div>
              <div class="carousel-item">
                <img src="{% static '/images/rain.jpg' %}" class="slide d-block w-100 " alt="...">
                <div class="carousel-caption d-none d-md-block">
                </div>
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
        </div>
    </div>
    <!--Banner 1-->
    <div class="partition mt-5">
      <div class="partition-heading text-center">
          <h2 style="font-family:open sans,sans-serif;">Explore Our Categories</h2>
      </div>
    </div>
    <div class="banner">
      <div class="container mt-3">
          <div class="row">
              <div class="col-lg-3 col-md-3 col-sm-3">
                  <div class="banner__pic" style="border-radius: 50%;overflow: hidden;border: 2px solid #d19547;">
                      <img src="{% static '/images/flats.jpg' %}" alt="" width=100% height=120%>
                  </div>
                  <div class="container-fluid">
                    <div class="text-center fs-5" style="font-style: italic;">
                    Shop by Type
                    </div>
                  </div>
              </div>
              <div class="col-lg-3 col-md-3 col-sm-3">
                  <div class="banner__pic" style="border-radius: 50%;overflow: hidden;border: 2px solid #d19547;">
                      <img src="{% static '/images/ocassion.jpg' %}" alt="" width=100% height=120%>
                  </div>
                  <div class="container-fluid">
                    <div class="text-center fs-5" style="font-style: italic;">
                    Shop For Occasion
                    </div>
                  </div>
              </div>
  
          <div class="col-lg-3 col-md-3 col-sm-3 text-center">
            <div class="banner__pic" style="border-radius: 50%;overflow: hidden;border: 2px solid #d19547;">
                <img src="{% static '/images/floalll.jpg' %}" alt="" width=100% height=120%>
            </div>
            <div class="container-fluid">
              <div class="text-center fs-5" style="font-style: italic;">
              Special Collection
              </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 col-sm-3">
                  <div class="banner__pic" style="border-radius: 50%;overflow: hidden;border: 2px solid #d19547;">
                      <img src="{% static '/images/shop.jpg' %}" alt="" width=100% height=120%>
                  </div>
                  <div class="container-fluid">
                    <div class="text-center fs-5" style="font-style: italic;">
                    Shop By Style
                    </div>
                  </div>
              </div>
  
      </div>
      </div>
    </div>
           
         <!--Product Section Begins here-->
            <div class="partition mt-5">
                <div class="partition-heading text-center">
                  {% if 'search' in request.path %}
                  <h2> Search Result</h2>
                  {% else %}
                    <h2 style="font-family:open sans,sans-serif;">Widest Range Collections</h2>
                  {% endif %}
                </div>
              
            </div>
          <section class="products">
              <div class="container">
                <div class="row">
                {% for variant in products %}
                <div class="col-md-3 mt-3 position-relative">
                  <div class="card" style="width:15rem; border:none" >
                    <a href="{% url 'products:singleproductview' product_id=variant.id %}">
                  <img src="/media/{{variant.product.images}}" class="card-img-top" alt="" ></a>
                    <div class="card-body text-center">
                    <h6 class="card-title text-center" id="namepr{{variant.product.id}}">{{variant.product.product_name}}</h6>
                    <p>Product ID: {{variant.product.id}}</p>
                    <div class="text-center">
                      <span class="price fw-bold">₹ {{variant.discount_price}}</span>
                      <del class="price-old">₹ {{variant.original_price}}</del>
                    </div>
                    <div class="featured-icons mt-2">
                      <a href="{% url 'dashboard:addwishlist' variant_id=variant.id%}" class="text-decoration-none"><i class="fa fa-heart text-success fs-5" title="Add to Wishlist"></i></a>
                      <a href="{% url 'cart:addcart' variant.id %}" class="text-decoration-none"><i class="fa fa-shopping-cart text-success fs-5" title="Add to Cart"></i></a>
                    </div>
                  </div>
                </div>
              </div>
                {% endfor %}
              </div>
            </div>
          </section>
  <!-- Banner Begin -->
<div class="banner">
  <div class="container mt-3">
      <div class="row">
          <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="banner__pic">
                  <img src="{% static '/images/banner/ban.png' %}" alt="" width=100% height=120%>
              </div>
          </div>
          <div class="col-lg-6 col-md-6 col-sm-6">
              <div class="banner__pic">
                  <img src="{% static '/images/banner/ban2.png' %}" alt="" width=100% height=120%>
              </div>
          </div>
      </div>
  </div>
</div>
<!-- Banner End -->

            <div class="container-fluid text-center" id="offer">
              <div class="row mt-5">
                  <div class="col-md-4 py-3 px-3 py-md-0">
                      <i class="text-dark fs-3 fa-solid fa-cart-shopping"></i>
                      <h5>Free Shipping</h5>
                      <p>On order over $100</p>
                  </div>
                  <div class="col-md-4 py-3 py-md-0">
                      <i class="text-dark fs-3 fa-solid fa-truck"></i>
                      <h5>Fast Delivery</h5>
                      <p>World wide</p>
                  </div>
                  <div class="col-md-4 py-3 py-md-0">
                      <i class="text-dark fs-3 fa-solid fa-thumbs-up"></i>
                      <h5>Best Quality</h5>
                      <p>Product</p>
                  </div>
              </div>
          </div>
    {% endblock %}

templates/user/login.html
{% extends 'user/base.html' %}
{% block title %}
login
{% endblock %}
{% block content %}
{% load static %}
<div class='container'>
    <div class='row'>
        <div class='col-md-4'>
            <div class="content">
                <img src="{% static '/images/loginn.jpg' %}" class="slide d-block w-100" alt="...">
                
            </div>
        </div>
        <div class='col-md-6 mt-3 bg-light'>
            <h3 class='text-secondary mt-3'>LOGIN</h3> 
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                 {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
            <div class="card-body "><!--not close-->
                <form method="post" action="{% url 'user:handlelogin' %}"><!--not close-->
                    {% csrf_token %}
                    <div class="form-group">
                        <label for = "email">Email</label>
                        <input type="text" class="form-control" name="email" id="email"
                               placeholder="Enter your Email">
                    </div>
                    <div class="form-group">
                        <label for = "password">Password</label>
                        <input type="password" class="form-control" name="password" id="password"
                               placeholder="Enter your password">
                    </div>
                    <div class="row justify-content-center">
                        <div class="col-md-6 text-center mt-3">
                            <button class="px-5 py-2 mt-3 bg-success rounded">Login</button>
                        </div>
                    </div>
                    <div class="text-center">
                        <a href="{% url 'user:handlesignup' %}" class="forgotpass  text-decoration-none text-dark">Join Now</a><br>
                        <a class="text-decoration-none fw-bold" href='{% url 'user:forgot_password' %}'>Forget your password ?</a>
                    </div>
                </form>
             </div>
      <!-- <form method="post" action="{% url 'user:handlelogin' %}">
        {% csrf_token %}
        <div class="form-group">
              <input type="email" class="form-control" name="email"
                                               placeholder="Enter your email">
        </div>
        <div class="form-group mt-3">
            <input type="password" class="form-control" name="password"
                                               placeholder="Enter your password">
        </div>

        <button class="px-5 py-2 mt-3 bg-success rounded">Login</button>
        <p class='mt-3'>Don't have an account? <a class="text-decoration-none fw-bold" href='{% url 'user:handlesignup' %}'>Join Now</a></p>
        <a class="text-decoration-none fw-bold" href='{% url 'user:forgot_password' %}'>Forget your password ?</a>
    </form>-->
        </div>
    </div>
    
</div>

                
                
{% endblock %}

templates/user/password_verify.html
{% autoescape off %}

Hi {{user.name}},

Please click on the below link to Reset your password.
http://{{domain}}{% url 'user:password_verify' uidb64=uid token=token %}

If you think it's not you, Please ignore this email.



{% endautoescape %}

templates/user/signup.html
{% extends 'user/base.html' %}
{% block title %}
signup
{% endblock %}
{% block content %}
{% load static %}
    <div class="container-fluid">
    <div class='row'>
        <div class='col-md-6'>
            <div class="content">
                <img src="{% static '/images/young.jpg' %}" class="slide d-block w-100" alt="...">
                
            </div>
        </div>
        <div class='col-md-5 bg-light'>
            <h3 class=' mt-1 text-secondary'>SIGN UP</h3>
            {% for message in messages %}
            <div class="alert alert-{{message.tags}} alert-dismissible fade show" role="alert">
                 {{message}}
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
              </div>
            {% endfor %}
    <form method='post' action='.'>
        {% csrf_token %}
        <div class='mt-4'>
            <input type="text" class="form-control" name="name" id="name"
                                   placeholder="Username" value="{{pre_name}}" required>
        </div>
        <div class='mt-3'>
            <input type="email" class="form-control" id="email" name="email"
                                   placeholder="Email" value="{{pre_email}}" required>
        </div>
        <div class='mt-3'>
            <input type="tel" class="form-control" name="mobile"
            placeholder="PhoneNumber" value="{{pre_mobile}}" required>
        </div>
        <div class='mt-3'>
            <input type="password" class="form-control" name="password1"
            placeholder="Password" required>
        </div>
        <div class='mt-3'>
            <input type="password" class="form-control" name="password2" id="password"
                                   placeholder="Confirm Password" required>
        </div>
        <div class='mt-3'>
        <input type="text" id="referral_code" name="referral_code" class="form-control" placeholder="Referral code" />
        </div>
        {% if form.errors or form.non_field_errors %}
            <div class='mb-3 p-6 bg-danger-100 rounded-xl'>
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}
                {{ form.non_field_errors }}

            </div>
        {% endif %}
        <button class="px-5 py-2 bg-success mt-3 rounded">Submit</button>
        <p class='mt-3'>Already have an account? <a class="text-decoration-none fw-bold" href='{% url 'user:handlelogin' %}'>Login</a></p>
    </form>
   
        </div>
    </div>
</div>
{% endblock %}
{% block 'j-script' %}

{% endblock %}